import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'muatmuat - Product Management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="en">
      <body className="bg-zinc-200">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  )
}
